---
- name: Playbook para automatizar la creación de particiones primarias LVM, Volume Group, Logical Volume y para Montar/Desmontar FS.
  hosts: all
  tasks:
    - name: Crear una nueva partición primaria LVM.
      parted:
        device: /dev/sdd
        number: 1
        flags: [ lvm ]
        state: present
        part_end: 7GB
      tags: create_pv

    - name: Realizar un pvcreate.
      shell: pvcreate /dev/sdd1
      tags: pvcreate

    - name: Crear volume group.
      lvg:
        vg: VG_LABS
        pvs: /dev/sdd1
        pesize: 5g
      tags: create_vg

    - name: Crear Logical Volume.
      lvol:
        vg: VG_LABS
        lv: LV_LABS
        size: +100%FREE
        force: yes
      tags: create_lv

    - name: Crea un sistema de archivos ext4 en /dev/VG_LAB/LV_LAB
      filesystem:
        fstype: ext4
        dev: /dev/VG_LAB/LV_LAB
      tags: create_fs_ext4

    - name: Crear directorio a montar.
      file:
        path: /datos/lab_directory
        state: directory
        mode: '0755'
      tags: create_directory

    - name: Montar FS.
      mount:
        path: /datos/lab_directory
        src: /dev/VG_LAB/LV_LAB
        fstype: ext4
        state: mounted
      tags: mount_fs